CC=gcc
CFLAGS=-std=c99 -Wall 
# -nostdinc

all:

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)

clean:
	rm -f *.o prog06??
	rm -f prog06??a
	rm -f prog06??b
	rm -f prog06??c
	rm -f prog06??d
	rm -f a.out galo totoloto
	rm -f *.gch
	rm -f *.swp
